export default {
    PORT : 8080,
    TIPO_DE_PERSISTENCIA_PRODUCTOS : "MONGODB",  //"MEM" "FILE" "MONGODB"
    TIPO_DE_PERSISTENCIA_CARRITO : "MONGODB",  //"MEM" "FILE" "MONGODB"
    STR_CNX : 'STR CNX'

}
